default: &default

  domain:                                alectrica.cl
  dominio:                               alectrica.cl
  tld:                                   alectrica

  #autorizacion server
  as:                                    https://autoriza.alectrica.cl

  #alectrica
  backend_alectrica_url:                 https://backend.alectrica.cl
  autorizador_alectrica_url:             https://autorizador.alectrica.cl

  #alectrico - se usa el domino alectrica por ahora
  frontend_alectrico_url:                https://frontend.alectrica.cl
  backend_alectrico_url:                 https://backend.alectrica.cl
  authentication_endpoint_alectrico_url: https://backend.alectrica.cl/authenticate
  retorno_exitoso_alectrico_url:         https://backend.alectrica.cl/authenticate#success=true

  #coronavid - se usa el domino alectrica por ahora, 
  frontend_coronavid_url:                https://frontend.alectrica.cl
  backend_coronavid_url:                 https://backend.alectrica.cl
  authentication_endpoint_coronavid_url: https://backend.alectrica.cl/authenticate
  help_url:                              https://help.alectrica.cl
  help_coronavid_url:                    https://help.alectrica.cl
  retorno_exitoso_url:                   https://backend.alectrica.cl/authenticate#success=true
  ok:                                    true


production:
  <<: *default

development:
  <<: *default

test:
  <<: *default




