copia_de_heroku:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 10
  database: db_copia_de_heroku
  #username: mooc_user
  password: '1'





development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 10
  database: db_gestion_development
  #database: rail_blog
  username: mooc_user
  #username: circleci-demo-ruby
  password: '1'
  #password: ''


test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 10
  #database: db_gestion_test
  database: rails_blog
  #username: mooc_user
  username: circleci-demo-ruby
  #password: '1'
  password: ''



electrico_heroku:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_GESTION_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>

alectrico_heroku:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_GESTION_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>


ci:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_GESTION_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>


