development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 10
  database: development
  #database: rails_blog
  username: mooc_user
  #username: circleci-demo-ruby
  password: '1'
  #password: ''

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 10
#  database: db_electrico_test
  database: rails_blog #Solo puedo usar esete en todo los focus(electrico, gestion, comercion, cargas) debido a que se usa para configurar la integración continua 
  #username: mooc_user
  username: circleci-demo-ruby
  #  username: read_user
  #password: '1'
  password: ''

electrico_heroku:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_ELECTRICO_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>



alectrico_heroku:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_ELECTRICO_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>


ci:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_ELECTRICO_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>



